name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev-asaleh  # ✅ Runs on push to `dev`

env:
  PROJECT_ID: curamet-onboarding
  REGION: europe-west1
  REPOSITORY: am-curamet-repo
  SERVICE_NAME: am-demo-service
  IMAGE_NAME: europe-docker.pkg.dev/curamet-onboarding/am-curamet-repo/am-demo-service

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # 3️⃣ Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # 4️⃣ Configure Docker Authentication
      - name: Authenticate Docker to Google Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      # 5️⃣ Build & Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      # 6️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          gcloud run deploy $SERVICE_NAME \
            --image=$IMAGE_NAME:$IMAGE_TAG \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated

      # 7️⃣ Output Cloud Run URL
      - name: Get Cloud Run Service URL
        run: gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)'
